version: '3'
services:
  hub:
    image: selenium/hub:3.141.59-yttrium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:3.141.59-yttrium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    ports:
      - "5902:5900"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox-debug:3.141.59-yttrium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    ports:
      - "5901:5000"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  github-test:
    image: github-test:1.0
    build:
      context: .
    depends_on:
      - hub
      - firefox
      - chrome
      - joomla
    volumes:
      - ./reports:/root/reports
      - ./resources:/root/scripts

  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8000:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
    volumes:
      - data:/var/www/html

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
    external: true
